In [47]:
## Python basics for novice data scientists, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2024 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2024-11-17 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2A_python_basic_course
# # @IDE     : Python 3.9
# # @File    : lec1_step9.py 

In [2]:
# module test: if you have an error when you run this code, 
# you need to check the installation status of those modules

import math 
import sys 
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patch
import matplotlib.cm as cm
import matplotlib as mp
import tkinter as tk

from pytictoc import TicToc 

In [13]:
hM=np.empty(5, dtype = object)
hM[0]

In [14]:
hM[0]=np.array([[5,0,3],[5,0,3],[5,0,3]])
hM[1]=np.array([[0,0,0],[4,0,3],[0,0,0]])
hM[2]=np.array([[0,0,0],[3,0,3],[0,0,0]])
hM[3]=np.array([[0,0,0],[2,0,3],[0,0,0]])
hM[4]=np.array([[0,0,0],[-5,-5,-5],[-5,-5,-5]])
hM

array([array([[5, 0, 3],
              [5, 0, 3],
              [5, 0, 3]]), array([[0, 0, 0],
                                  [4, 0, 3],
                                  [0, 0, 0]]), array([[0, 0, 0],
                                                      [3, 0, 3],
                                                      [0, 0, 0]]),
       array([[0, 0, 0],
              [2, 0, 3],
              [0, 0, 0]]), array([[ 0,  0,  0],
                                  [-5, -5, -5],
                                  [-5, -5, -5]])], dtype=object)

In [27]:
len(hM)


5

In [4]:
conM=np.array([[1,0,0],[1,1,1],[0,1,0]])


In [52]:
conM_full=np.empty(5, dtype = object)
for i in range(4):
    conM_full[i]=conM

conM_full

array([array([[1, 0, 0],
              [1, 1, 1],
              [0, 1, 0]]), array([[1, 0, 0],
                                  [1, 1, 1],
                                  [0, 1, 0]]), array([[1, 0, 0],
                                                      [1, 1, 1],
                                                      [0, 1, 0]]),
       array([[1, 0, 0],
              [1, 1, 1],
              [0, 1, 0]]), None], dtype=object)

In [53]:
np.array([[5,0,3],[5,0,3],[5,0,3]]).T

array([[5, 5, 5],
       [0, 0, 0],
       [3, 3, 3]])

In [54]:
# hM[0]=np.array([[5,0,3],[5,0,3],[5,0,3]]).T
# hM[1]=np.array([[0,0,0],[4,0,3],[0,0,0]]).T
# hM[2]=np.array([[0,0,0],[3,0,3],[0,0,0]]).T
# hM[3]=np.array([[0,0,0],[2,0,3],[0,0,0]]).T
# hM[4]=np.array([[0,0,0],[-5,-5,-5],[-5,-5,-5]]).T
# hM

In [55]:
np.tile([1,2,3],[3,1])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [56]:
# F=[0,0,0]

In [57]:
np.max(hM[0],axis=1)


array([5, 5, 5])

In [15]:
hM[1]

array([[0, 0, 0],
       [4, 0, 3],
       [0, 0, 0]])

In [58]:
np.max(hM[0],axis=0)


array([5, 0, 3])

In [59]:
np.transpose([np.max(hM[0],axis=1)])

array([[5],
       [5],
       [5]])

In [60]:
Ft=[0,0,0]

In [24]:
Ft=np.array([5, 0, 3])

In [25]:
(np.tile(Ft.T,[3,1]).T+hM[1])*conM

array([[5, 0, 0],
       [4, 0, 3],
       [0, 3, 0]])

In [26]:
np.max((np.tile(Ft.T,[3,1]).T+hM[1])*conM,axis=0)

array([5, 3, 3])

In [30]:
conM1=np.array([[1,0,0],[1,1,1],[0,1,0]])

Ft=[0,0,0]
for h in hM:
    Ft=np.max((np.tile(Ft,[3,1]).T+h)*conM,axis=0)
    print(Ft)
    

[5 0 3]
[5 3 3]
[6 3 6]
[6 6 6]
[6 1 1]


In [36]:
conM=np.empty(len(hM), dtype = object)
conM[:-1]=1
conM[-1]=2
conM

array([1, 1, 1, 1, 2], dtype=object)

In [43]:
conM1=np.array([[1,0,0],[1,1,1],[0,1,0]])
conM=[conM1 for i in range(len(hM))]
conM[-1]=np.array([[1,0,0],[1,0,0],[1,0,0]])
conM

[array([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 0]]),
 array([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 0]]),
 array([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 0]]),
 array([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 0]]),
 array([[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]])]

In [38]:
conM[-1]=np.array([[1,0,0],[1,1,1],[0,1,0]])


In [56]:
Ft=[0,0,0]
for h,c in zip(hM,conM):
    body=(np.tile(Ft,[3,1]).T+h)*c
    Ft=np.max(body,axis=0)
    iD=np.argmax(body,axis=0)
    Ft_full.append(Ft)
    iD_full.append(iD)
    # print(body)
    print(Ft)
    print(iD)

[5 0 3]
[0 0 1]
[5 3 3]
[0 2 1]
[6 3 6]
[1 1 1]
[6 6 6]
[0 2 1]
[6 0 0]
[0 0 0]


In [144]:
sampleList=list(range(10))
sampleList

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [145]:
sampleList[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [146]:
sampleList[-2::-1]

[8, 7, 6, 5, 4, 3, 2, 1, 0]

In [148]:
sampleList[-2:3:-1]

[8, 7, 6, 5, 4]

In [149]:
sampleList[3:-2:1]

[3, 4, 5, 6, 7]

In [143]:
# Algorithm 5.1: completed version of dynamic programming


conM1=np.array([[1,0,0],[1,1,1],[0,1,0]])
conM=[conM1 for i in range(len(hM))]
conM[-1]=np.array([[1,0,0],[1,0,0],[1,0,0]])
conM[0]=np.array([[0,0,0],[1,1,1],[0,0,0]])
display(conM)
print('~forward~~')

Ft_full=[]
iD_full=[]

Ft=[0,0,0]
for h,c in zip(hM,conM):
    body=(np.tile(Ft,[3,1]).T+h)*c
    Ft=np.max(body,axis=0)
    iD=np.argmax(body,axis=0)
    Ft_full.append(Ft)
    iD_full.append(iD)
    # print(body)
    print(iD,Ft)

print('~backward~~')
# Ft_full=np.array(Ft_full)
# iD_full=np.array(iD_full)
# print(Ft_full,iD_full)
poslist=[]
vallist=[]
endNode=np.argmax(Ft)
poslist.append(endNode)
pre_pos=iD[endNode]
vallist.append(np.max(Ft))
poslist.append(pre_pos)
print(np.max(Ft))
for iD,Ft in zip(iD_full[-2::-1],Ft_full[-2::-1]):
    vallist.append(Ft[pre_pos])
    pre_pos=iD[pre_pos]
    poslist.append(pre_pos)
    print(Ft[pre_pos])
vallist.append(Ft[pre_pos])
print(poslist,vallist)

Path=poslist[::-1]
Valp=vallist[::-1]

print(f'Path = {Path}')
print(f'max(Ft) = {Valp}')
# print('Fval = '+Valp)

[array([[0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]]),
 array([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 0]]),
 array([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 0]]),
 array([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 0]]),
 array([[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]])]

~forward~~
[1 0 1] [5 0 3]
[0 2 1] [5 3 3]
[1 1 1] [6 3 6]
[0 2 1] [6 6 6]
[0 0 0] [6 0 0]
~backward~~
6
6
3
3
0
[0, 0, 0, 1, 2, 1] [6, 6, 6, 3, 3, 0]
Path = [1, 2, 1, 0, 0, 0]
Fval = [0, 3, 3, 6, 6, 6]


In [20]:
np.max((np.tile(Ft.T,[1,3])+hM[1])*conM,axis=0)

array([5, 3, 3])

In [22]:
np.max((np.tile(Ft.T,[1,3])+hM[1])*conM,axis=0)

array([5, 3, 3])

In [61]:
# (np.tile(F,[3,1])+hM[0])

In [62]:
F=np.full((1,3),[0,0,0])
iD=np.full((1,3),[0,0,0])
display(F)
display(iD)

array([[0, 0, 0]])

array([[0, 0, 0]])

In [79]:
Ft=[0,0,0]
iDt=[0,0,0]
display(Ft)
display(iDt)

[0, 0, 0]

[0, 0, 0]

In [64]:
Ft=np.max(conM*np.tile(Ft,[3,1]).T+hM[0],axis=0)
iDt=np.argmax(conM*np.tile(Ft,[3,1]).T+hM[0],axis=0)
display(Ft)
F=np.vstack([F,Ft])
iD=np.vstack([iD,iDt])
display(F)
display(iD)

array([5, 0, 3])

array([[0, 0, 0],
       [5, 0, 3]])

array([[0, 0, 0],
       [0, 2, 0]])

In [65]:
Ft=np.max(conM*np.tile(Ft,[3,1]).T+hM[1],axis=0)
iDt=np.argmax(conM*np.tile(Ft,[3,1]).T+hM[0],axis=0)
display(Ft)
F=np.vstack([F,Ft])
iD=np.vstack([iD,iDt])
display(F)
display(iD)

array([5, 3, 3])

array([[0, 0, 0],
       [5, 0, 3],
       [5, 3, 3]])

array([[0, 0, 0],
       [0, 2, 0],
       [0, 1, 1]])

In [66]:
Ft=np.max(conM*np.tile(Ft,[3,1]).T+hM[2],axis=0)
iDt=np.argmax(conM*np.tile(Ft,[3,1]).T+hM[0],axis=0)

display(Ft)
F=np.vstack([F,Ft])
iD=np.vstack([iD,iDt])
display(F)
display(iD)

array([6, 3, 6])

array([[0, 0, 0],
       [5, 0, 3],
       [5, 3, 3],
       [6, 3, 6]])

array([[0, 0, 0],
       [0, 2, 0],
       [0, 1, 1],
       [0, 2, 1]])

In [67]:
Ft=np.max(conM*np.tile(Ft,[3,1]).T+hM[3],axis=0)
iDt=np.argmax(conM*np.tile(Ft,[3,1]).T+hM[0],axis=0)

display(Ft)
F=np.vstack([F,Ft])
iD=np.vstack([iD,iDt])
display(F)
display(iD)

array([6, 6, 6])

array([[0, 0, 0],
       [5, 0, 3],
       [5, 3, 3],
       [6, 3, 6],
       [6, 6, 6]])

array([[0, 0, 0],
       [0, 2, 0],
       [0, 1, 1],
       [0, 2, 1],
       [0, 1, 1]])

In [68]:
Ft=np.max(conM*np.tile(Ft,[3,1]).T+hM[0],axis=0)
iDt=np.argmax(conM*np.tile(Ft,[3,1]).T+hM[0],axis=0)
display(Ft)
F=np.vstack([F,Ft])
iD=np.vstack([iD,iDt])
display(F)
display(iD)

array([11,  6,  9])

array([[ 0,  0,  0],
       [ 5,  0,  3],
       [ 5,  3,  3],
       [ 6,  3,  6],
       [ 6,  6,  6],
       [11,  6,  9]])

array([[0, 0, 0],
       [0, 2, 0],
       [0, 1, 1],
       [0, 2, 1],
       [0, 1, 1],
       [0, 2, 1]])

In [69]:
Ft=np.max(conM*np.tile(Ft,[3,1]).T+hM[1],axis=0)
iDt=np.argmax(conM*np.tile(Ft,[3,1]).T+hM[1],axis=0)
display(Ft)
F=np.vstack([F,Ft])
iD=np.vstack([iD,iDt])
display(F)
display(iD)

array([11,  9,  9])

array([[ 0,  0,  0],
       [ 5,  0,  3],
       [ 5,  3,  3],
       [ 6,  3,  6],
       [ 6,  6,  6],
       [11,  6,  9],
       [11,  9,  9]])

array([[0, 0, 0],
       [0, 2, 0],
       [0, 1, 1],
       [0, 2, 1],
       [0, 1, 1],
       [0, 2, 1],
       [1, 1, 1]])

In [70]:
Ft=np.max(conM*np.tile(Ft,[3,1]).T+hM[2],axis=0)
iDt=np.argmax(conM*np.tile(Ft,[3,1]).T+hM[2],axis=0)
display(Ft)
F=np.vstack([F,Ft])
iD=np.vstack([iD,iDt])
display(F)
display(iD)

array([12,  9, 12])

array([[ 0,  0,  0],
       [ 5,  0,  3],
       [ 5,  3,  3],
       [ 6,  3,  6],
       [ 6,  6,  6],
       [11,  6,  9],
       [11,  9,  9],
       [12,  9, 12]])

array([[0, 0, 0],
       [0, 2, 0],
       [0, 1, 1],
       [0, 2, 1],
       [0, 1, 1],
       [0, 2, 1],
       [1, 1, 1],
       [0, 2, 1]])

In [71]:
Ft=np.max(conM*np.tile(Ft,[3,1]).T+hM[3],axis=0)
iDt=np.argmax(conM*np.tile(Ft,[3,1]).T+hM[3],axis=0)
display(Ft)
F=np.vstack([F,Ft])
iD=np.vstack([iD,iDt])
display(F)
display(iD)

array([12, 12, 12])

array([[ 0,  0,  0],
       [ 5,  0,  3],
       [ 5,  3,  3],
       [ 6,  3,  6],
       [ 6,  6,  6],
       [11,  6,  9],
       [11,  9,  9],
       [12,  9, 12],
       [12, 12, 12]])

array([[0, 0, 0],
       [0, 2, 0],
       [0, 1, 1],
       [0, 2, 1],
       [0, 1, 1],
       [0, 2, 1],
       [1, 1, 1],
       [0, 2, 1],
       [1, 1, 1]])

In [72]:
display(iD)

array([[0, 0, 0],
       [0, 2, 0],
       [0, 1, 1],
       [0, 2, 1],
       [0, 1, 1],
       [0, 2, 1],
       [1, 1, 1],
       [0, 2, 1],
       [1, 1, 1]])

In [73]:
np.tile(Ft,[3,1]).T

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [74]:
conM*np.tile(Ft,[3,1]).T

array([[12,  0,  0],
       [12, 12, 12],
       [ 0, 12,  0]])

In [75]:
np.dot(conM,np.tile(Ft,[3,1]).T)

array([[12, 12, 12],
       [36, 36, 36],
       [12, 12, 12]])

In [76]:
Ft

array([12, 12, 12])

In [77]:
# F=np.max(np.tile(F,[3,1])+hM[1],axis=0)
F

array([[ 0,  0,  0],
       [ 5,  0,  3],
       [ 5,  3,  3],
       [ 6,  3,  6],
       [ 6,  6,  6],
       [11,  6,  9],
       [11,  9,  9],
       [12,  9, 12],
       [12, 12, 12]])

In [78]:
F

array([[ 0,  0,  0],
       [ 5,  0,  3],
       [ 5,  3,  3],
       [ 6,  3,  6],
       [ 6,  6,  6],
       [11,  6,  9],
       [11,  9,  9],
       [12,  9, 12],
       [12, 12, 12]])