In [1]:
# Practice 3-3 (page 24/29)
# https://www.slideshare.net/tadahirotaniguchi0624/3-46861684

In [9]:
import numpy as np

list_0 = [
        [9, 8, 5],
        [0, 8, 3],
        [1, 6, 5],
        [9, 0, 0],
        [4, 9, 3],
        [1, 4, 8],
        [4, 0, 6],
        [0, 3, 5],
        [1, 3, 1],
        [5, 2, 7],
    ]
list_np=np.array(list_0)
print(list_np)


[[9 8 5]
 [0 8 3]
 [1 6 5]
 [9 0 0]
 [4 9 3]
 [1 4 8]
 [4 0 6]
 [0 3 5]
 [1 3 1]
 [5 2 7]]


In [6]:
print(list_np[:,0])

[9 0 1 9 4 1 4 0 1 5]


In [7]:
print(list_np[0,:])

[9 8 5]
