In [1]:
## Python basics for novice data scientists, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2020 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2022-12-29 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2A_python_basic_course
# # @IDE     : Python 3.9.16 (main, Dec  7 2022, 10:15:43) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : lec2_step03.py 

In [2]:
# module test: if you have an error when you run this code, 
# you need to check the installation status of those modules

import math 
import sys 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.animation as animation

import tkinter as tk

In [3]:
import matplotlib.pyplot as plt
%matplotlib tk

In [4]:
# References:
# https://matplotlib.org/stable/gallery/animation/pause_resume.html
# https://qiita.com/yubais/items/c95ba9ff1b23dd33fde2

In [3]:
np.random.randn(3,3)

array([[-1.43101722, -0.5288764 , -0.79520694],
       [ 0.52171351, -0.42252011,  0.33131452],
       [ 0.43283754, -1.10393478,  1.16268898]])

In [4]:
a=np.random.rand(5,5)
print(a)
print('-')
print(a[1,1])

[[0.40952068 0.06167711 0.39854297 0.79022479 0.62797906]
 [0.2749292  0.62913523 0.87602546 0.81896538 0.02961105]
 [0.76605505 0.85420685 0.75859196 0.57755562 0.50852946]
 [0.77257478 0.93036308 0.90521603 0.33912855 0.64735726]
 [0.4708376  0.34069124 0.50246758 0.15272056 0.88957592]]
-
0.6291352317727321


In [5]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

figNum=10
NofD=20
NofD=5
maxR=np.array([0,1])

fig = plt.figure(figNum)
plot_frames = []

plt.xticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
plt.yticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
plt.axis('equal')
plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis

for i in range(NofD):
        randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
        each_plot = plt.plot(randPos[0],randPos[1],'.',markersize=14)  # save the plot into a frame
        plot_frames.append(each_plot)                  # append the frame to array

# showing N  frames of plot every 1000ms 
animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1000)
plt.show()


2025-02-01 22:04:15.064 Python[37105:47441343] +[IMKClient subclass]: chose IMKClient_Legacy
2025-02-01 22:04:15.064 Python[37105:47441343] +[IMKInputSession subclass]: chose IMKInputSession_Legacy


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

maxR=np.array([0,1])

figNum=11
fig = plt.figure(figNum,figsize = (5, 5))

def plotP(frame_id):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
    plt.yticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(randPos[0],randPos[1],'.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    plt.title(frame_id)


animatedP = animation.FuncAnimation(fig, plotP, interval=100)
plt.show()

animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

/var/folders/mg/w5t8lkhc8xj79f001s7kzpfh0000gp/T/ipykernel_36991/2860197164.py:26: UserWarning: frames=None which we can infer the length of, did not pass an explicit *save_count* and passed cache_frame_data=True.  To avoid a possibly unbounded cache, frame data caching has been disabled. To suppress this warning either pass `cache_frame_data=False` or `save_count=MAX_FRAMES`.
  animatedP = animation.FuncAnimation(fig, plotP, interval=100)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py:872: UserWarning: Animation was deleted without rendering anything. This is most likely not intended. To prevent deletion, assign the Animation to a variable, e.g. `anim`, that exists until you output the Animation using `plt.show()` or `anim.save()`.
  warnings.warn(


<Figure size 500x500 with 0 Axes>

MovieWriter imagemagick unavailable; using Pillow instead.


In [6]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

maxR=np.array([0,1])

figNum=12
fig = plt.figure(figNum,figsize = (5, 5))

def plotP(frame_id):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
    plt.yticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(randPos[0],randPos[1],'.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    plt.title(frame_id)


animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 200)
plt.show()

animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

MovieWriter imagemagick unavailable; using Pillow instead.


In [7]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

maxR=np.array([0,1])

figNum=13
fig = plt.figure(figNum,figsize = (5, 5))

def plotP(frame_id,pramA,pramB):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
    plt.yticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(pramA*randPos[0],pramA*randPos[1],'.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    plt.title(pramB+': '+str(frame_id))


pramA=0.5
pramB='Random Points'
animatedP = animation.FuncAnimation(fig, plotP, fargs = (pramA, pramB), interval=100)
plt.show()

# animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

/var/folders/mg/w5t8lkhc8xj79f001s7kzpfh0000gp/T/ipykernel_37105/1726840040.py:28: UserWarning: frames=None which we can infer the length of, did not pass an explicit *save_count* and passed cache_frame_data=True.  To avoid a possibly unbounded cache, frame data caching has been disabled. To suppress this warning either pass `cache_frame_data=False` or `save_count=MAX_FRAMES`.
  animatedP = animation.FuncAnimation(fig, plotP, fargs = (pramA, pramB), interval=100)


In [10]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

NofD=4
pStep=8
maxR=np.array([-5,5])

figNum=15
fig = plt.figure(figNum,figsize = (5, 5))

rotA=lambda th: [[np.cos(th), -np.sin(th)],[np.sin(th),np.cos(th)]]

def plotP(frame_id,pramA,pramB):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1], 1))
    plt.yticks(np.arange(maxR[0], maxR[1], 1))
    plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
    plt.title("Points")   # title of the plot
    plt.xlabel("x")      # label in x axis
    plt.ylabel("y")      # label in y axis

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    angD=frame_id/pStep*np.pi
    dataD=pramA
    dataD=np.dot(rotA(angD),dataD)
    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(dataD[0],dataD[1],'b.',markersize=14)                       # save the plot into a frame
    node_plot = plt.plot(dataD[0][0],dataD[1][0],'r.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    
    ang180=np.mod(angD/np.pi*180,360)
    strD='{:02.1f}'.format(ang180)
    plt.title(pramB+': '+strD)


# dataD=np.array([[1, -1,-1,1],[1,1,-1,-1]])
# dataD=np.dot(rotA(np.pi/4),dataD)

pramA=np.array([[1, -1,-1,1],[1,1,-1,-1]])
pramB='Angle'
animatedP = animation.FuncAnimation(fig, plotP, fargs = (pramA, pramB), interval=1000,frames = 200)
plt.show()

animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

MovieWriter imagemagick unavailable; using Pillow instead.


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

NofD=4
pStep=8
maxR=np.array([-5,5])

figNum=15
fig = plt.figure(figNum,figsize = (5, 5))

rotA=lambda th: [[np.cos(th), -np.sin(th)],[np.sin(th),np.cos(th)]]

def plotP(frame_id,pramA,pramB):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1], 1))
    plt.yticks(np.arange(maxR[0], maxR[1], 1))
    plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
    plt.title("Points")   # title of the plot
    plt.xlabel("x")      # label in x axis
    plt.ylabel("y")      # label in y axis

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    angD=frame_id/pStep*np.pi
    dataD=pramA
    dataD=np.dot(rotA(angD),dataD)
    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(dataD[0],dataD[1],'b.',markersize=14)                       # save the plot into a frame
    node_plot = plt.plot(dataD[0][0],dataD[1][0],'r.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    
    ang180=np.mod(angD/np.pi*180,360)
    strD='{:02.1f}'.format(ang180)
    plt.title(pramB+': '+strD)


# dataD=np.array([[1, -1,-1,1],[1,1,-1,-1]])
# dataD=np.dot(rotA(np.pi/4),dataD)

pramA=np.array([[1, -1,-1,1],[1,1,-1,-1]])
pramB='Angle'
animatedP = animation.FuncAnimation(fig, plotP, fargs = (pramA, pramB), interval=1000,frames = 200)
plt.show()

animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

In [ ]:
figure(1);
clf;

roadLabel={'road1','road2','road3'};

mapDx=[-100,100; 0,0; 0,100 ];
mapDy=[0,0;-100,100;80,80 ];

plot(mapDx',mapDy','LineWidth',2);
legend(roadLabel);
grid on;
axis equal;


In [18]:
mapDx

array([[-100,  100],
       [   0,    0],
       [   0,  100]])

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/backends/_backend_tk.py", line 142, in _on_timer
    super()._on_timer()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1179, in _on_timer
    ret = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py", line 1411, in _step
    self._init_draw()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py", line 1485, in _init_draw
    fig.canvas.

In [3]:
figNum=10
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

roadLabel=['road1','road2','road3']
mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.xticks(np.arange(maxR[0], maxR[1], 10))
plt.yticks(np.arange(maxR[0], maxR[1], 10))
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')

NofT=1
for i in range(NofT):
        each_plot = plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)  # save the plot into a frame
        plot_frames.append(each_plot)                  # append the frame to array

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1)
plt.show()


2025-02-04 20:51:34.009 Python[92053:51417691] +[IMKClient subclass]: chose IMKClient_Legacy
2025-02-04 20:51:34.009 Python[92053:51417691] +[IMKInputSession subclass]: chose IMKInputSession_Legacy


In [4]:
figNum=11
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

roadLabel=['road1','road2','road3']
mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.xticks(np.arange(maxR[0], maxR[1], 10))
plt.yticks(np.arange(maxR[0], maxR[1], 10))
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')

plt.plot(mapDx.T,mapDy.T,'-',linewidth=2) 

# NofT=1
# for i in range(NofT):
#         each_plot = plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)  # save the plot into a frame
#         plot_frames.append(each_plot)                  # append the frame to array

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1)
plt.show()


In [24]:
v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]
display(cPx)

roadLabel=['road1','road2','road3']
vehi_Label=['vehicle1','vehicle2']
all_Lable=roadLabel+vehi_Label
display(all_Lable)


array([-80,   0])

['road1', 'road2', 'road3', 'vehicle1', 'vehicle2']

In [21]:
all_Lable

['road1', 'road2', 'road3', 'vehicle1', 'vehicle2']

In [12]:
figNum=12
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

NofT=1
each_plot=[]
for i in range(len(cPx)):
        each_plot.append(plt.plot(cPx[i],cPy[i],'.',markersize=20))  # save the plot into a frame
        
plot_frames.append(each_plot)                  # append the frame to array

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=10)
animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1,repeat=False)
plt.show()

fig.legend(all_Lable)

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/cbook.py", line 298, in process
    func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py", line 892, in _start
    self._init_draw()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py", line 1477, in _init_draw
    artist.set_visible(False)
AttributeError: 'list' object has no attribute 'set_visible'


In [13]:
figNum=12
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

NofT=1
# each_plot=[]
for i in range(len(cPx)):
    if i==0:
        each_plot=plt.plot(cPx[i],cPy[i],'.',markersize=20)  # save the plot into a frame
    else:
        each_plot.append(plt.plot(cPx[i],cPy[i],'.',markersize=20))  # save the plot into a frame
        
plot_frames.append(each_plot)                  # append the frame to array

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=10)
animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1,repeat=False)
plt.show()

fig.legend(all_Lable)

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/cbook.py", line 298, in process
    func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py", line 892, in _start
    self._init_draw()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py", line 1477, in _init_draw
    artist.set_visible(False)
AttributeError: 'list' object has no attribute 'set_visible'


In [4]:
figNum=13
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

# NofT=1
# each_plot=[]
# for i in range(len(cPx)):
#         each_plot.append(plt.plot(cPx[i],cPy[i],'.',markersize=20))  # save the plot into a frame
        
# plot_frames.append(each_plot)                  # append the frame to array

simT=100
NofC=2

for i2 in range(simT):
    tP=i2/simT
    tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
    tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))
    each_plot=[]
    for x,y in zip(tmpx,tmpy):
        each_plot=plt.plot(x,y,'.',markersize=20)
    # each_plot=[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]
        plot_frames.append(each_plot)

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=10)
animatedP = animation.ArtistAnimation(fig, plot_frames, interval=10)
plt.show()

fig.legend(all_Lable)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py:872: UserWarning: Animation was deleted without rendering anything. This is most likely not intended. To prevent deletion, assign the Animation to a variable, e.g. `anim`, that exists until you output the Animation using `plt.show()` or `anim.save()`.
  warnings.warn(


2025-02-04 22:40:20.397 Python[2474:26846] +[IMKClient subclass]: chose IMKClient_Modern
2025-02-04 22:40:20.397 Python[2474:26846] +[IMKInputSession subclass]: chose IMKInputSession_Modern


In [4]:
figNum=16
maxR=[-100,100]
fig = plt.figure(figNum)

fig.clear()
plt.cla()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

# plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

simT=100
NofC=2

def plotP(i2):
    plt.cla() 
    plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)
    tP=i2/simT
    tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
    tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))

    each_plot=[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]
    plot_frames.append(each_plot)

animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20, repeat=False)
# animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20)

plt.show()

fig.legend(all_Lable)

2025-02-04 23:12:42.952 Python[4112:74901] +[IMKClient subclass]: chose IMKClient_Modern
2025-02-04 23:12:42.952 Python[4112:74901] +[IMKInputSession subclass]: chose IMKInputSession_Modern


In [19]:
Moby=np.array(3*[[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])      
Rot=lambda t: np.array([[np.cos(t),-np.sin(t)],[np.sin(t),np.cos(t)]])
display(Rot(np.pi))
cLen=np.abs(min(Moby[1,:])-max(Moby[1,:]))
cLen

array([[-1.0000000e+00, -1.2246468e-16],
       [ 1.2246468e-16, -1.0000000e+00]])

3.3

In [20]:
lane_x = mapDx.copy()
lane_y = mapDy.copy()

In [156]:
lane_x,lane_y

(array([[-100,  100],
        [   0,    0],
        [   0,  100]]),
 array([[   0,    0],
        [-100,  100],
        [  80,   80]]))

In [32]:
-np.arctan2(np.diff(y),np.diff(x))

array([-0.])

In [113]:
roadW=10
x=lane_x[0]
y=lane_y[0]
-np.arctan2(np.diff(y),np.diff(x))
np.cos(-np.arctan2(np.diff(y),np.diff(x)))
Rot(-np.arctan2(np.diff(y),np.diff(x))).reshape(2,2)
np.dot(Rot(-np.arctan2(np.diff(y),np.diff(x))).reshape(2,2),[np.diff(x),np.diff(y)])

vecR=[np.sqrt(np.diff(x)**2+np.diff(y)**2).T for x,y in zip(lane_x,lane_y)]
angL=[np.arctan2(np.diff(y),np.diff(x)) for x,y in zip(lane_x,lane_y)]
Rvec=[np.dot(Rot(-th).reshape(2,2),[np.diff(x),np.diff(y)]).T for x,y,th in zip(lane_x,lane_y,angL)]
# Rvec=[np.dot(Rot(-np.arctan2(np.diff(y),np.diff(x))).reshape(2,2),[np.diff(x),np.diff(y)]).T for x,y in zip(lane_x,lane_y)]
np.dot(Rvec,[[1,1],[-10,10]])

Rvec
# np.tile(Rvec[0],[2,1])+[[0,]],roadW/2]

[array([[200.,   0.]]),
 array([[2.0000000e+02, 1.2246468e-14]]),
 array([[100.,   0.]])]

In [73]:
vecR=[np.sqrt(np.diff(x)**2+np.diff(y)**2).T for x,y in zip(lane_x,lane_y)]
vecR

[array([200.]), array([200.]), array([100.])]

In [172]:
x=lane_x[0]
y=lane_y[0]
rotXY3[3]+np.array([[x[0]]*2,[y[0]]*2]).T

array([[-100.,   -5.],
       [-100.,    5.]])

In [189]:
len(rotXY3)


6

In [212]:
# ([lane_x[:,0]]**2).tolist()
(np.tile(lane_x[:,0],[1,2])[0]).tolist()

[-100, 0, 0, -100, 0, 0]

In [214]:
roadW=10
rotXY=[np.tile(v,[2,1])+roadW/2*np.array([[0,0],[-1,1]]).T for v in Rvec]
# display(rotXY)
rotXY2=[v-r*np.array([[1,1],[0,0]]).T for v,r in zip(rotXY,vecR)]
# display(rotXY2)
rotXY3=[np.dot(Rot(th).reshape(2,2),v.T).T for v,th in zip(rotXY+rotXY2,np.array(angL*2))]
display(rotXY3)
rotXY4=[v+np.array([[x]*2,[y]*2]).T for v,x,y in zip(rotXY3,(np.tile(lane_x[:,0],[1,2])[0]).tolist(),(np.tile(lane_y[:,0],[1,2])[0]).tolist())]
rotXY4

[array([[200.,  -5.],
        [200.,   5.]]),
 array([[  5., 200.],
        [ -5., 200.]]),
 array([[100.,  -5.],
        [100.,   5.]]),
 array([[ 0., -5.],
        [ 0.,  5.]]),
 array([[ 5.000000e+00, -3.061617e-16],
        [-5.000000e+00,  3.061617e-16]]),
 array([[ 0., -5.],
        [ 0.,  5.]])]

[array([[100.,  -5.],
        [100.,   5.]]),
 array([[  5., 100.],
        [ -5., 100.]]),
 array([[100.,  75.],
        [100.,  85.]]),
 array([[-100.,   -5.],
        [-100.,    5.]]),
 array([[   5., -100.],
        [  -5., -100.]]),
 array([[ 0., 75.],
        [ 0., 85.]])]

In [157]:
rotXY3

[array([[200.,  -5.],
        [200.,   5.]]),
 array([[  5., 200.],
        [ -5., 200.]]),
 array([[100.,  -5.],
        [100.,   5.]]),
 array([[ 0., -5.],
        [ 0.,  5.]]),
 array([[ 5.000000e+00, -3.061617e-16],
        [-5.000000e+00,  3.061617e-16]]),
 array([[ 0., -5.],
        [ 0.,  5.]])]

In [215]:

figNum=18
maxR=[-100,100]
fig = plt.figure(figNum)

fig.clear()
plt.cla()
for p2,p1 in zip(rotXY4[:len(rotXY)],rotXY4[len(rotXY):]):
    plt.plot(np.vstack([p1[:,0],p2[:,0]]),np.vstack([p1[:,1],p2[:,1]]),'-',linewidth=2)


In [226]:
roadW=10

lane_x = mapDx.copy()
lane_y = mapDy.copy()

vecR=[np.sqrt(np.diff(x)**2+np.diff(y)**2).T for x,y in zip(lane_x,lane_y)]
angL=[np.arctan2(np.diff(y),np.diff(x)) for x,y in zip(lane_x,lane_y)]
Rvec=[np.dot(Rot(-th).reshape(2,2),[np.diff(x),np.diff(y)]).T for x,y,th in zip(lane_x,lane_y,angL)]

rotXY=[np.tile(v,[2,1])+roadW/2*np.array([[0,0],[-1,1]]).T for v in Rvec]
rotXY2=[v-r*np.array([[1,1],[0,0]]).T for v,r in zip(rotXY,vecR)]
rotXY3=[np.dot(Rot(th).reshape(2,2),v.T).T for v,th in zip(rotXY+rotXY2,np.array(angL*2))]
rotXY4=[v+np.array([[x]*2,[y]*2]).T for v,x,y in zip(rotXY3,(np.tile(lane_x[:,0],[1,2])[0]).tolist(),(np.tile(lane_y[:,0],[1,2])[0]).tolist())]

figNum=18
maxR=[-100,100]
fig = plt.figure(figNum)

fig.clear()
plt.cla()
for p2,p1 in zip(rotXY4[:len(rotXY)],rotXY4[len(rotXY):]):
    plt.plot(np.vstack([p1[:,0],p2[:,0]]),np.vstack([p1[:,1],p2[:,1]]),'-',linewidth=2)

my_color1=np.array([122,122,122])
# plt.plot(lane_x,lane_y,color=my_color1,lineWidth=3)
plt.plot(lane_x.T,lane_y.T,'--',color="0.5",linewidth=2)



In [227]:
Moby=np.array(3*[[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])      
Rot=lambda t: np.array([[np.cos(t),-np.sin(t)],[np.sin(t),np.cos(t)]])
display(Rot(np.pi))
cLen=np.abs(min(Moby[1,:])-max(Moby[1,:]))
cLen

array([[-1.0000000e+00, -1.2246468e-16],
       [ 1.2246468e-16, -1.0000000e+00]])

3.3

In [230]:
figNum=19
maxR=[-100,100]
fig = plt.figure(figNum)

fig.clear()
plt.cla()
plt.plot(Moby[0],Moby[1],'-',linewidth=2)



plt.xticks(np.arange(maxR[0], maxR[1], 10))
plt.yticks(np.arange(maxR[0], maxR[1], 10))
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')


(-1.1, 1.1, -1.715, 1.915)

In [228]:
Moby[0]

array([-0.6 ,  0.6 ,  1.  ,  1.  ,  0.75, -0.75, -1.  , -1.  , -0.6 ,
        0.6 ])

In [232]:
angL2=angL[:-1]
angL2

[array([0.]), array([1.57079633])]

In [235]:
figNum=19
maxR=[-100,100]
fig = plt.figure(figNum)
NofC=2

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0
initPx=v_planning_x[:,0]
initPy=v_planning_y[:,0]

display(initPx)

sign2=lambda a,b: np.sign(((a>=0).astype(int)-0.5)*((b>=0).astype(int)-0.5))

# for x,y in zip(initPx,initPy): 
# xu,xd,yu,yd=(initPx[0]-lane_x[:,0]),np.diff(lane_x).T[0],(initPy[0]-lane_y[:,0]),np.diff(lane_y).T[0]
# np.where((sign2(xu,xd)>=0) & (xu<=xd) & (sign2(yu,yd)>=0) & (yu<=yd))[0]

# xu,xd,yu,yd=(x-lane_x[:,0]),np.diff(lane_x).T[0],(y-lane_y[:,0]),np.diff(lane_y).T[0]
cLaneID=[np.where((sign2((x-lane_x[:,0]),np.diff(lane_x).T[0])>=0) & ((x-lane_x[:,0])<=np.diff(lane_x).T[0]) & (sign2((y-lane_y[:,0]),np.diff(lane_y).T[0])>=0) & ((y-lane_y[:,0])<=np.diff(lane_y).T[0]))[0] 
 for x,y in zip(initPx,initPy)]



# for j in range(NofC):
#     currPosMo=Rot(cPos(j,3)-pi/2)*Moby+repmat(cPos(j,1:2)',[1 size(Moby,2)]);
#     pc{j,1}=plot(currPosMo(1,:),currPosMo(2,:),'-','LineWidth',3,'color',ccol(j,:)); 
#     pc{j,2}=plot(cPos(j,1),cPos(j,2),'.','MarkerSize',22); 
# end

array([-80,   0])

array([[-100,  100],
       [   0,    0],
       [   0,  100]])

In [370]:
np.empty([1,3])
initPx=np.array([-80,   0.1])
initPx

array([-80. ,   0.1])

In [372]:
cPos=np.empty([NofC,3])
display(cPos)
np.vstack([initPx,initPy]).T

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[-80. ,   0. ],
       [  0.1, -80. ]])

In [386]:
cPos[:,:2]
cLaneID2=np.array(cLaneID)
np.array(angL)[cLaneID2]

array([[[0.        ]],

       [[1.57079633]]])

In [390]:
cPos=np.empty([NofC,3])
cPos[:,:2]=np.vstack([initPx,initPy]).T
# cPos[:,2]=np.array(angL)[cLaneID2]
cPos[:,2]=np.array(angL)[cLaneID2].T
cPos

array([[-80.        ,   0.        ,   0.        ],
       [  0.1       , -80.        ,   1.57079633]])

In [392]:
Rot(cPos[j,2]-np.pi/2)

array([[ 6.123234e-17,  1.000000e+00],
       [-1.000000e+00,  6.123234e-17]])

In [399]:
Moby=3*np.array([[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])  
# Moby=[]
Moby

array([[-1.8 ,  1.8 ,  3.  ,  3.  ,  2.25, -2.25, -3.  , -3.  , -1.8 ,
         1.8 ],
       [ 5.25,  5.25,  2.25, -3.75, -4.65, -4.65, -3.75,  2.25,  5.25,
         5.25]])

In [400]:
np.dot(Rot(cPos[j,2]-np.pi/2),Moby)

array([[ 5.25,  5.25,  2.25, -3.75, -4.65, -4.65, -3.75,  2.25,  5.25,
         5.25],
       [ 1.8 , -1.8 , -3.  , -3.  , -2.25,  2.25,  3.  ,  3.  ,  1.8 ,
        -1.8 ]])

In [404]:
np.shape(Moby)[1]


10

In [409]:
[cPos[0,:2]]

[array([-80.,   0.])]

In [411]:
np.tile(cPos[0,:2],[np.shape(Moby)[1],1]).T

array([[-80., -80., -80., -80., -80., -80., -80., -80., -80., -80.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [413]:
for j in range(NofC):
    # currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+repmat(cPos(j,1:2)',[1 size(Moby,2)]);
    currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+np.tile(cPos[0,:2],[np.shape(Moby)[1],1]).T
currPosMo

array([[-81.8 , -78.2 , -77.  , -77.  , -77.75, -82.25, -83.  , -83.  ,
        -81.8 , -78.2 ],
       [  5.25,   5.25,   2.25,  -3.75,  -4.65,  -4.65,  -3.75,   2.25,
          5.25,   5.25]])

In [431]:
figNum=20
fig = plt.figure(figNum)
fig.clear()
plt.cla()
maxR=[-100,100]


Moby=3*np.array([[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])      
Rot=lambda t: np.array([[np.cos(t),-np.sin(t)],[np.sin(t),np.cos(t)]])
cLen=np.abs(min(Moby[1,:])-max(Moby[1,:]))


cPos=np.empty([NofC,3])
cPos[:,:2]=np.vstack([initPx,initPy]).T
cPos[:,2]=np.array(angL)[cLaneID2].T

for j in range(NofC):
    # currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+repmat(cPos(j,1:2)',[1 size(Moby,2)]);
    currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+np.tile(cPos[j,:2],[np.shape(Moby)[1],1]).T
    plt.plot(currPosMo[0],currPosMo[1],'k-',linewidth=2)


for p2,p1 in zip(rotXY4[:len(rotXY)],rotXY4[len(rotXY):]):
    plt.plot(np.vstack([p1[:,0],p2[:,0]]),np.vstack([p1[:,1],p2[:,1]]),'-',linewidth=2)

my_color1=np.array([122,122,122])
# plt.plot(lane_x,lane_y,color=my_color1,lineWidth=3)
plt.plot(lane_x.T,lane_y.T,'--',color="0.5",linewidth=2)


# plt.xticks(np.arange(maxR[0], maxR[1], 10))
# plt.yticks(np.arange(maxR[0], maxR[1], 10))
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')

# def plotP(i2):
#     plt.cla() 
#     plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)
#     tP=i2/simT
#     tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
#     tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))

#     each_plot=[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]
#     plot_frames.append(each_plot)

# animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20, repeat=False)
# # animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20)

# plt.show()

# fig.legend(all_Lable)

(-110.0, 110.0, -110.0, 110.0)

In [435]:
figNum=21
fig = plt.figure(figNum)
fig.clear()
plt.cla()
maxR=[-100,100]


Moby=3*np.array([[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])      
Rot=lambda t: np.array([[np.cos(t),-np.sin(t)],[np.sin(t),np.cos(t)]])
cLen=np.abs(min(Moby[1,:])-max(Moby[1,:]))


# cPos=np.empty([NofC,3])
# cPos[:,:2]=np.vstack([initPx,initPy]).T
# cPos[:,2]=np.array(angL)[cLaneID2].T

# for j in range(NofC):
#     # currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+repmat(cPos(j,1:2)',[1 size(Moby,2)]);
#     currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+np.tile(cPos[j,:2],[np.shape(Moby)[1],1]).T
#     plt.plot(currPosMo[0],currPosMo[1],'k-',linewidth=2)


# for p2,p1 in zip(rotXY4[:len(rotXY)],rotXY4[len(rotXY):]):
#     plt.plot(np.vstack([p1[:,0],p2[:,0]]),np.vstack([p1[:,1],p2[:,1]]),'-',linewidth=2)

my_color1=np.array([122,122,122])
# plt.plot(lane_x,lane_y,color=my_color1,lineWidth=3)
# plt.plot(lane_x.T,lane_y.T,'--',color="0.5",linewidth=2)


# plt.xticks(np.arange(maxR[0], maxR[1], 10))
# plt.yticks(np.arange(maxR[0], maxR[1], 10))
# plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')

def plotP(i2):
    plt.cla() 
    plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

    for p2,p1 in zip(rotXY4[:len(rotXY)],rotXY4[len(rotXY):]):
        plt.plot(np.vstack([p1[:,0],p2[:,0]]),np.vstack([p1[:,1],p2[:,1]]),'-',linewidth=2)

    my_color1=np.array([122,122,122])
    # plt.plot(lane_x,lane_y,color=my_color1,lineWidth=3)
    plt.plot(lane_x.T,lane_y.T,'--',color="0.5",linewidth=2)

    # plt.title("Time")   # title of the plot
    plt.title(f'Time: {i2}')
    plt.xlabel("x")      # label in x axis
    plt.ylabel("y")      # label in y axis
    
    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis
    plt.axis('equal')

    # plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)
    tP=i2/simT
    tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
    tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))

    cPos[:,:2]=np.vstack([tmpx,tmpy]).T
    # cPos[:,2]=np.array(angL)[cLaneID2].T

    each_plot=[]
    for j in range(NofC):
        # currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+repmat(cPos(j,1:2)',[1 size(Moby,2)]);
        currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+np.tile(cPos[j,:2],[np.shape(Moby)[1],1]).T
        each_plot.append(plt.plot(currPosMo[0],currPosMo[1],'k-',linewidth=2))


    each_plot2=[plt.plot(x,y,'.',markersize=10) for x,y in zip(tmpx,tmpy)]
    each_plot3=each_plot+each_plot2
    
    plot_frames.append(each_plot3)

animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 100, repeat=False)
# # animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20)

plt.show()

fig.legend(all_Lable)

In [416]:
currPosMo

array([[-81.8 , -78.2 , -77.  , -77.  , -77.75, -82.25, -83.  , -83.  ,
        -81.8 , -78.2 ],
       [  5.25,   5.25,   2.25,  -3.75,  -4.65,  -4.65,  -3.75,   2.25,
          5.25,   5.25]])

In [349]:
cLaneID=[np.where((sign2((x-lane_x[:,0]),np.diff(lane_x).T[0])>=0) & ((x-lane_x[:,0])<=np.diff(lane_x).T[0]) & (sign2((y-lane_y[:,0]),np.diff(lane_y).T[0])>=0) & ((y-lane_y[:,0])<=np.diff(lane_y).T[0]))[0] 
 for x,y in zip(initPx,initPy)]
cLaneID

[array([0]), array([1])]

In [351]:
np.array(cLaneID)[0]

array([0])

In [347]:
[np.where((sign2((x-lane_x[:,0]),np.diff(lane_x).T[0])>=0) & ((x-lane_x[:,0])<=np.diff(lane_x).T[0]) & (sign2((y-lane_y[:,0]),np.diff(lane_y).T[0])>=0) & ((y-lane_y[:,0])<=np.diff(lane_y).T[0]))[0] for x,y in zip(initPx,initPy)]


[array([0]), array([1])]

In [241]:
np.sign(-1)>0

False

In [278]:
initPx[0],initPy[0]

(-80, 0)

In [263]:
xu,xd,yu,yd=(initPx[0]-lane_x[:,0]),np.diff(lane_x).T[0],(initPy[0]-lane_y[:,0]),np.diff(lane_y).T[0]

In [271]:
np.where((np.sign(xu*xd)>=0) & (xu<=xd) & (np.sign(yu*yd)>=0) & (yu<=yd))

(array([0, 1]),)

In [279]:
lane_x,lane_y

(array([[-100,  100],
        [   0,    0],
        [   0,  100]]),
 array([[   0,    0],
        [-100,  100],
        [  80,   80]]))

In [281]:
sign2=lambda x: np.sign(x) if len(np.where(xu==0)[0])==0 else 1
sign2(0)

1

In [345]:
sign2=lambda a,b: np.sign(((a>=0).astype(int)-0.5)*((b>=0).astype(int)-0.5))

In [296]:
yu=np.array([  0, 0, -80])
yu

array([  0,   0, -80])

In [311]:
yu[np.where(yu==0)[0]]=np.tile(0.1,[1,2])
yu[np.where(yu==0)[0]]

yu[np.where(yu==0)[0]]
# yu[np.where(yu==0)[0]]

array([0, 0])

In [312]:
yu[np.where(yu==0)[0]]

array([0, 0])

In [314]:
yu[0]=yu[0]+0.1
yu[0]

0

In [317]:
yu[0]=yu[0]+0.1
[ for k in np.where(yu==0)[0]]

0

In [343]:
yu,yd

(array([  0,   0, -80]), array([  0, 200, -10]))

In [344]:
np.sign(((yu>=0).astype(int)-0.5)*((yd>=0).astype(int)-0.5))


array([1., 1., 1.])

In [340]:
((yu>=0).astype(int)-0.5)

array([ 0.5,  0.5, -0.5])

In [341]:
((yd>=0).astype(int)-0.5)

array([ 0.5,  0.5, -0.5])

In [337]:
(yu>=0).astype(int)

array([1, 1, 0])

In [325]:
(yu>=0) & (yd>=0)

array([ True,  True, False])

In [335]:
yu[0]=0.1
yd[2]=-10
yd

array([  0, 200, -10])

In [ ]:
sign2(xu)*sign2(xd)

In [346]:
sign2=lambda a,b: np.sign(((a>=0).astype(int)-0.5)*((b>=0).astype(int)-0.5))
np.where((sign2(xu,xd)>=0) & (xu<=xd) & (sign2(xu,xd)>=0) & (yu<=yd))[0]

array([0])

In [275]:
np.sign(xu*xd)>=0

array([ True,  True, False])

In [274]:
xu<=xd

array([ True,  True,  True])

In [273]:
np.sign(yu*yd)>=0

array([ True,  True,  True])

In [272]:
yu<=yd

array([ True,  True,  True])

In [258]:
(initPx[0]-lane_x[:,0])

array([ 20, -80, -80])

In [255]:
np.diff(lane_x).T[0]

array([200,   0, 100])

In [261]:
(initPx[0]-lane_x[:,0])*np.diff(lane_x).T[0]>=0

array([ True,  True, False])

In [ ]:
np.sign()

In [254]:
(initPx[0]-lane_x[:,0])<np.diff(lane_x).T[0]

array([ True,  True,  True])

In [239]:
lane_x-initPx[0]

array([[-20, 180],
       [ 80,  80],
       [ 80, 180]])

In [123]:
np.array(rotXY3).reshape(len(lane_x)*4,2).T

array([[ 2.000000e+02,  2.000000e+02,  5.000000e+00, -5.000000e+00,
         1.000000e+02,  1.000000e+02,  0.000000e+00,  0.000000e+00,
         5.000000e+00, -5.000000e+00,  0.000000e+00,  0.000000e+00],
       [-5.000000e+00,  5.000000e+00,  2.000000e+02,  2.000000e+02,
        -5.000000e+00,  5.000000e+00, -5.000000e+00,  5.000000e+00,
        -3.061617e-16,  3.061617e-16, -5.000000e+00,  5.000000e+00]])

In [107]:
np.array(rotXY3)

array([[[ 200.,  200.],
        [  -5.,    5.]],

       [[  -5.,    5.],
        [-200., -200.]],

       [[ 100.,  100.],
        [  -5.,    5.]]])

In [138]:
len(rotXY)

3

In [87]:
len(rotXY+rotXY2)

6

In [103]:
len(lane_x)*4

12

In [98]:
k=1
v=rotXY[k]
th=angL[k]
np.dot(Rot(th).reshape(2,2),v.T)

array([[  -5.,    5.],
       [-200., -200.]])

In [99]:
Rot(th).reshape(2,2)

array([[ 6.123234e-17,  1.000000e+00],
       [-1.000000e+00,  6.123234e-17]])

In [100]:
v.T

array([[200., 200.],
       [ -5.,   5.]])

In [59]:
angL=[np.arctan2(np.diff(y),np.diff(x)) for x,y in zip(lane_x,lane_y)]
angL=[np.dot(Rot(-np.arctan2(np.diff(y),np.diff(x))),[np.diff(y),np.diff(x)]) for x,y in zip(lane_x,lane_y)]
# [Rot(-a) for a in angL]

ValueError: shapes (2,2,1) and (2,1) not aligned: 1 (dim 2) != 2 (dim 0)

In [ ]:
figNum=17
maxR=[-100,100]
fig = plt.figure(figNum)

Moby=np.array(3*[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6;1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75];      
Rot=@(t) [cos(t),-sin(t); sin(t),cos(t)];
cLen=abs(min(Moby(2,:))-max(Moby(2,:)));

fig.clear()
plt.cla()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

# plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

simT=100
NofC=2

def plotP(i2):
    plt.cla() 
    plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)
    tP=i2/simT
    tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
    tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))

    each_plot=[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]
    plot_frames.append(each_plot)

animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20, repeat=False)
# animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20)

plt.show()

fig.legend(all_Lable)

array([78.4,  0. ])

In [30]:
tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))
tmpx
[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]

[[<matplotlib.lines.Line2D at 0x30a1a0bb0>],

In [22]:
[v_planning_x].T

AttributeError: 'list' object has no attribute 'T'

array([[-80,  80],
       [  0,   0]])

In [16]:
[[1-tP,tP]].T

[1, 0]

In [ ]:
https://numpy.org/doc/2.1/reference/generated/numpy.dot.html
https://numpy.org/doc/2.1/reference/generated/numpy.matmul.html#numpy.matmul

In [ ]:
https://qiita.com/Yuu-Miino/items/ae7d9c78bc2dff6c9a51

In [27]:
np.dot(v_planning_x[1],np.array([1-tP,tP]))

0

In [ ]:

NofC=2;
simT=100;
vC=[50,40]; # %50km/h*1000(k)/3600(s)
#% frate=0.1;
frate=1

v_planning_x=[-80,80; 0,0;];
v_planning_y=[0,0;-80,80;];
tP=0;

cPx=v_planning_x(:,2).*tP+v_planning_x(:,1).*(1-tP);
cPy=v_planning_y(:,2).*tP+v_planning_y(:,1).*(1-tP);

roadLabel={'road1','road2','road3'};
vehi_Label={'vehicle1','vehicle2'};
all_Lable=roadLabel;
all_Lable(end+1:end+length(vehi_Label))=vehi_Label;

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plot(mapDx',mapDy','LineWidth',2),hold on;

vehiP={};
for i=1:NofC
    vehiP{i}=plot(cPx(i)',cPy(i)','.','Color',myCol(i,:),'MarkerSize',50);
end

legend(all_Lable);
grid on;
axis equal;
tPv=repmat(tP,[1,2]);

for i2=1:simT
% %     tPv=tPv+(vC*1000/3600).*frate;
    tP=i2/simT;
    tPv=repmat(tP,[1,2]);
    tmpx=diag(v_planning_x*[(1-tPv);tPv]);
    tmpy=diag(v_planning_y*[(1-tPv);tPv]);
    
    for i=1:NofC
        set(vehiP{i},'XData',tmpx(i),'YData',tmpy(i));
    end
%     pause(0.1);
    drawnow;
end
