In [1]:
## Python basics for novice data scientists, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2020 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2022-12-29 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2A_python_basic_course
# # @IDE     : Python 3.9.16 (main, Dec  7 2022, 10:15:43) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : lec2_step03.py 

In [1]:
# module test: if you have an error when you run this code, 
# you need to check the installation status of those modules

import math 
import sys 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.animation as animation

import tkinter as tk

In [2]:
import matplotlib.pyplot as plt
%matplotlib tk

In [4]:
# References:
# https://matplotlib.org/stable/gallery/animation/pause_resume.html
# https://qiita.com/yubais/items/c95ba9ff1b23dd33fde2

In [5]:
np.random.randn(3,3)

array([[-0.66916458, -0.56739664, -0.38530255],
       [ 1.56205372, -0.61012223,  2.58797566],
       [ 0.12516336, -0.14482283, -0.56071745]])

In [6]:
a=np.random.rand(5,5)
print(a)
print('-')
print(a[1,1])

[[0.03127564 0.90631963 0.78806701 0.8572176  0.36266855]
 [0.20469768 0.89760855 0.57393779 0.9614299  0.85331704]
 [0.60650955 0.70430263 0.15116719 0.65964691 0.04332869]
 [0.04280422 0.34592027 0.40926594 0.37899745 0.80084002]
 [0.47224776 0.81260612 0.67291742 0.7561735  0.74699996]]
-
0.8976085540649238


In [3]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

figNum=10
NofD=20
NofD=5
maxR=np.array([0,1])

fig = plt.figure(figNum)
plot_frames = []

plt.xticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
plt.yticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
plt.axis('equal')
plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis

for i in range(NofD):
        randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
        each_plot = plt.plot(randPos[0],randPos[1],'.',markersize=14)  # save the plot into a frame
        plot_frames.append(each_plot)                  # append the frame to array

# showing N  frames of plot every 1000ms 
animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1000)
plt.show()


2025-02-06 22:31:45.606 Python[10098:2435702] +[IMKClient subclass]: chose IMKClient_Modern
2025-02-06 22:31:45.606 Python[10098:2435702] +[IMKInputSession subclass]: chose IMKInputSession_Modern


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

maxR=np.array([0,1])

figNum=11
fig = plt.figure(figNum,figsize = (5, 5))

def plotP(frame_id):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
    plt.yticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(randPos[0],randPos[1],'.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    plt.title(frame_id)


animatedP = animation.FuncAnimation(fig, plotP, interval=100)
plt.show()

animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

/var/folders/mg/w5t8lkhc8xj79f001s7kzpfh0000gp/T/ipykernel_1039/2860197164.py:26: UserWarning: frames=None which we can infer the length of, did not pass an explicit *save_count* and passed cache_frame_data=True.  To avoid a possibly unbounded cache, frame data caching has been disabled. To suppress this warning either pass `cache_frame_data=False` or `save_count=MAX_FRAMES`.
  animatedP = animation.FuncAnimation(fig, plotP, interval=100)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/animation.py:872: UserWarning: Animation was deleted without rendering anything. This is most likely not intended. To prevent deletion, assign the Animation to a variable, e.g. `anim`, that exists until you output the Animation using `plt.show()` or `anim.save()`.
  warnings.warn(
MovieWriter imagemagick unavailable; using Pillow instead.


In [4]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

maxR=np.array([0,1])

figNum=12
fig = plt.figure(figNum,figsize = (5, 5))

def plotP(frame_id):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
    plt.yticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(randPos[0],randPos[1],'.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    plt.title(frame_id)


animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 200)
plt.show()

animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

MovieWriter imagemagick unavailable; using Pillow instead.


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

maxR=np.array([0,1])

figNum=13
fig = plt.figure(figNum,figsize = (5, 5))

def plotP(frame_id,pramA,pramB):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))
    plt.yticks(np.arange(maxR[0], maxR[1]+0.2, 0.2))

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(pramA*randPos[0],pramA*randPos[1],'.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    plt.title(pramB+': '+str(frame_id))


pramA=0.5
pramB='Random Points'
animatedP = animation.FuncAnimation(fig, plotP, fargs = (pramA, pramB), interval=100)
plt.show()

# animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

NofD=4
pStep=8
maxR=np.array([-5,5])

figNum=15
fig = plt.figure(figNum,figsize = (5, 5))

rotA=lambda th: [[np.cos(th), -np.sin(th)],[np.sin(th),np.cos(th)]]

def plotP(frame_id,pramA,pramB):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1], 1))
    plt.yticks(np.arange(maxR[0], maxR[1], 1))
    plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
    plt.title("Points")   # title of the plot
    plt.xlabel("x")      # label in x axis
    plt.ylabel("y")      # label in y axis

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    angD=frame_id/pStep*np.pi
    dataD=pramA
    dataD=np.dot(rotA(angD),dataD)
    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(dataD[0],dataD[1],'b.',markersize=14)                       # save the plot into a frame
    node_plot = plt.plot(dataD[0][0],dataD[1][0],'r.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    
    ang180=np.mod(angD/np.pi*180,360)
    strD='{:02.1f}'.format(ang180)
    plt.title(pramB+': '+strD)


# dataD=np.array([[1, -1,-1,1],[1,1,-1,-1]])
# dataD=np.dot(rotA(np.pi/4),dataD)

pramA=np.array([[1, -1,-1,1],[1,1,-1,-1]])
pramB='Angle'
animatedP = animation.FuncAnimation(fig, plotP, fargs = (pramA, pramB), interval=1000,frames = 200)
plt.show()

animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

NofD=4
pStep=8
maxR=np.array([-5,5])

figNum=15
fig = plt.figure(figNum,figsize = (5, 5))

rotA=lambda th: [[np.cos(th), -np.sin(th)],[np.sin(th),np.cos(th)]]

def plotP(frame_id,pramA,pramB):
    plt.cla()                      #  clearn-up the current plot
#     plt.axis('equal')    
    plt.xticks(np.arange(maxR[0], maxR[1], 1))
    plt.yticks(np.arange(maxR[0], maxR[1], 1))
    plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
    plt.title("Points")   # title of the plot
    plt.xlabel("x")      # label in x axis
    plt.ylabel("y")      # label in y axis

    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis

    angD=frame_id/pStep*np.pi
    dataD=pramA
    dataD=np.dot(rotA(angD),dataD)
    
    randPos = np.random.rand(NofD,NofD)     #  NofD x NofD points are generated randomly
    each_plot = plt.plot(dataD[0],dataD[1],'b.',markersize=14)                       # save the plot into a frame
    node_plot = plt.plot(dataD[0][0],dataD[1][0],'r.',markersize=14)                       # save the plot into a frame
    plot_frames.append(each_plot)                  # append the frame to array
    
    ang180=np.mod(angD/np.pi*180,360)
    strD='{:02.1f}'.format(ang180)
    plt.title(pramB+': '+strD)


# dataD=np.array([[1, -1,-1,1],[1,1,-1,-1]])
# dataD=np.dot(rotA(np.pi/4),dataD)

pramA=np.array([[1, -1,-1,1],[1,1,-1,-1]])
pramB='Angle'
animatedP = animation.FuncAnimation(fig, plotP, fargs = (pramA, pramB), interval=1000,frames = 200)
plt.show()

animatedP.save('anime'+str(figNum)+'.gif', writer = 'imagemagick')

In [ ]:
figure(1);
clf;

roadLabel={'road1','road2','road3'};

mapDx=[-100,100; 0,0; 0,100 ];
mapDy=[0,0;-100,100;80,80 ];

plot(mapDx',mapDy','LineWidth',2);
legend(roadLabel);
grid on;
axis equal;


In [ ]:
mapDx

In [ ]:
figNum=10
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

roadLabel=['road1','road2','road3']
mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.xticks(np.arange(maxR[0], maxR[1], 10))
plt.yticks(np.arange(maxR[0], maxR[1], 10))
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')

NofT=1
for i in range(NofT):
        each_plot = plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)  # save the plot into a frame
        plot_frames.append(each_plot)                  # append the frame to array

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1)
plt.show()


In [ ]:
figNum=11
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

roadLabel=['road1','road2','road3']
mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.xticks(np.arange(maxR[0], maxR[1], 10))
plt.yticks(np.arange(maxR[0], maxR[1], 10))
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')

plt.plot(mapDx.T,mapDy.T,'-',linewidth=2) 

# NofT=1
# for i in range(NofT):
#         each_plot = plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)  # save the plot into a frame
#         plot_frames.append(each_plot)                  # append the frame to array

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1)
plt.show()


In [ ]:
v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]
display(cPx)

roadLabel=['road1','road2','road3']
vehi_Label=['vehicle1','vehicle2']
all_Lable=roadLabel+vehi_Label
display(all_Lable)


In [ ]:
all_Lable

In [ ]:
figNum=12
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

NofT=1
each_plot=[]
for i in range(len(cPx)):
        each_plot.append(plt.plot(cPx[i],cPy[i],'.',markersize=20))  # save the plot into a frame
        
plot_frames.append(each_plot)                  # append the frame to array

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=10)
animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1,repeat=False)
plt.show()

fig.legend(all_Lable)

In [ ]:
figNum=12
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

NofT=1
# each_plot=[]
for i in range(len(cPx)):
    if i==0:
        each_plot=plt.plot(cPx[i],cPy[i],'.',markersize=20)  # save the plot into a frame
    else:
        each_plot.append(plt.plot(cPx[i],cPy[i],'.',markersize=20))  # save the plot into a frame
        
plot_frames.append(each_plot)                  # append the frame to array

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=10)
animatedP = animation.ArtistAnimation(fig, plot_frames, interval=1,repeat=False)
plt.show()

fig.legend(all_Lable)

In [ ]:
figNum=13
maxR=[-100,100]
fig = plt.figure(figNum)
fig.clf()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

# NofT=1
# each_plot=[]
# for i in range(len(cPx)):
#         each_plot.append(plt.plot(cPx[i],cPy[i],'.',markersize=20))  # save the plot into a frame
        
# plot_frames.append(each_plot)                  # append the frame to array

simT=100
NofC=2

for i2 in range(simT):
    tP=i2/simT
    tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
    tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))
    each_plot=[]
    for x,y in zip(tmpx,tmpy):
        each_plot=plt.plot(x,y,'.',markersize=20)
    # each_plot=[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]
        plot_frames.append(each_plot)

# animatedP = animation.ArtistAnimation(fig, plot_frames, interval=10)
animatedP = animation.ArtistAnimation(fig, plot_frames, interval=10)
plt.show()

fig.legend(all_Lable)

In [ ]:
figNum=16
maxR=[-100,100]
fig = plt.figure(figNum)

fig.clear()
plt.cla()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

# plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

simT=100
NofC=2

def plotP(i2):
    plt.cla() 
    plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)
    tP=i2/simT
    tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
    tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))

    each_plot=[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]
    plot_frames.append(each_plot)

animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20, repeat=False)
# animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20)

plt.show()

fig.legend(all_Lable)

In [ ]:
Moby=np.array(3*[[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])      
Rot=lambda t: np.array([[np.cos(t),-np.sin(t)],[np.sin(t),np.cos(t)]])
display(Rot(np.pi))
cLen=np.abs(min(Moby[1,:])-max(Moby[1,:]))
cLen

In [ ]:
lane_x = mapDx.copy()
lane_y = mapDy.copy()

In [ ]:
lane_x,lane_y

In [ ]:
-np.arctan2(np.diff(y),np.diff(x))

In [ ]:
roadW=10
x=lane_x[0]
y=lane_y[0]
-np.arctan2(np.diff(y),np.diff(x))
np.cos(-np.arctan2(np.diff(y),np.diff(x)))
Rot(-np.arctan2(np.diff(y),np.diff(x))).reshape(2,2)
np.dot(Rot(-np.arctan2(np.diff(y),np.diff(x))).reshape(2,2),[np.diff(x),np.diff(y)])

vecR=[np.sqrt(np.diff(x)**2+np.diff(y)**2).T for x,y in zip(lane_x,lane_y)]
angL=[np.arctan2(np.diff(y),np.diff(x)) for x,y in zip(lane_x,lane_y)]
Rvec=[np.dot(Rot(-th).reshape(2,2),[np.diff(x),np.diff(y)]).T for x,y,th in zip(lane_x,lane_y,angL)]
# Rvec=[np.dot(Rot(-np.arctan2(np.diff(y),np.diff(x))).reshape(2,2),[np.diff(x),np.diff(y)]).T for x,y in zip(lane_x,lane_y)]
np.dot(Rvec,[[1,1],[-10,10]])

Rvec
# np.tile(Rvec[0],[2,1])+[[0,]],roadW/2]

In [ ]:
vecR=[np.sqrt(np.diff(x)**2+np.diff(y)**2).T for x,y in zip(lane_x,lane_y)]
vecR

In [ ]:
x=lane_x[0]
y=lane_y[0]
rotXY3[3]+np.array([[x[0]]*2,[y[0]]*2]).T

In [ ]:
len(rotXY3)


In [ ]:
# ([lane_x[:,0]]**2).tolist()
(np.tile(lane_x[:,0],[1,2])[0]).tolist()

In [ ]:
roadW=10
rotXY=[np.tile(v,[2,1])+roadW/2*np.array([[0,0],[-1,1]]).T for v in Rvec]
# display(rotXY)
rotXY2=[v-r*np.array([[1,1],[0,0]]).T for v,r in zip(rotXY,vecR)]
# display(rotXY2)
rotXY3=[np.dot(Rot(th).reshape(2,2),v.T).T for v,th in zip(rotXY+rotXY2,np.array(angL*2))]
display(rotXY3)
rotXY4=[v+np.array([[x]*2,[y]*2]).T for v,x,y in zip(rotXY3,(np.tile(lane_x[:,0],[1,2])[0]).tolist(),(np.tile(lane_y[:,0],[1,2])[0]).tolist())]
rotXY4

In [ ]:
rotXY3

In [ ]:

figNum=18
maxR=[-100,100]
fig = plt.figure(figNum)

fig.clear()
plt.cla()
for p2,p1 in zip(rotXY4[:len(rotXY)],rotXY4[len(rotXY):]):
    plt.plot(np.vstack([p1[:,0],p2[:,0]]),np.vstack([p1[:,1],p2[:,1]]),'-',linewidth=2)


In [ ]:
Moby=np.array(3*[[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])      
Rot=lambda t: np.array([[np.cos(t),-np.sin(t)],[np.sin(t),np.cos(t)]])
display(Rot(np.pi))
cLen=np.abs(min(Moby[1,:])-max(Moby[1,:]))

roadW=10

lane_x = mapDx.copy()
lane_y = mapDy.copy()

vecR=[np.sqrt(np.diff(x)**2+np.diff(y)**2).T for x,y in zip(lane_x,lane_y)]
angL=[np.arctan2(np.diff(y),np.diff(x)) for x,y in zip(lane_x,lane_y)]
Rvec=[np.dot(Rot(-th).reshape(2,2),[np.diff(x),np.diff(y)]).T for x,y,th in zip(lane_x,lane_y,angL)]

rotXY=[np.tile(v,[2,1])+roadW/2*np.array([[0,0],[-1,1]]).T for v in Rvec]
rotXY2=[v-r*np.array([[1,1],[0,0]]).T for v,r in zip(rotXY,vecR)]
rotXY3=[np.dot(Rot(th).reshape(2,2),v.T).T for v,th in zip(rotXY+rotXY2,np.array(angL*2))]
rotXY4=[v+np.array([[x]*2,[y]*2]).T for v,x,y in zip(rotXY3,(np.tile(lane_x[:,0],[1,2])[0]).tolist(),(np.tile(lane_y[:,0],[1,2])[0]).tolist())]

figNum=18
maxR=[-100,100]
fig = plt.figure(figNum)

fig.clear()
plt.cla()
for p2,p1 in zip(rotXY4[:len(rotXY)],rotXY4[len(rotXY):]):
    plt.plot(np.vstack([p1[:,0],p2[:,0]]),np.vstack([p1[:,1],p2[:,1]]),'-',linewidth=2)

my_color1=np.array([122,122,122])
# plt.plot(lane_x,lane_y,color=my_color1,lineWidth=3)
plt.plot(lane_x.T,lane_y.T,'--',color="0.5",linewidth=2)



In [ ]:
Moby=np.array(3*[[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])      
Rot=lambda t: np.array([[np.cos(t),-np.sin(t)],[np.sin(t),np.cos(t)]])
display(Rot(np.pi))
cLen=np.abs(min(Moby[1,:])-max(Moby[1,:]))
cLen

In [ ]:
figNum=19
maxR=[-100,100]
fig = plt.figure(figNum)

fig.clear()
plt.cla()
plt.plot(Moby[0],Moby[1],'-',linewidth=2)



plt.xticks(np.arange(maxR[0], maxR[1], 10))
plt.yticks(np.arange(maxR[0], maxR[1], 10))
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')


In [ ]:
Moby[0]

In [ ]:
angL2=angL[:-1]
angL2

In [ ]:
figNum=19
maxR=[-100,100]
fig = plt.figure(figNum)
NofC=2

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0
initPx=v_planning_x[:,0]
initPy=v_planning_y[:,0]

display(initPx)

sign2=lambda a,b: np.sign(((a>=0).astype(int)-0.5)*((b>=0).astype(int)-0.5))

# for x,y in zip(initPx,initPy): 
# xu,xd,yu,yd=(initPx[0]-lane_x[:,0]),np.diff(lane_x).T[0],(initPy[0]-lane_y[:,0]),np.diff(lane_y).T[0]
# np.where((sign2(xu,xd)>=0) & (xu<=xd) & (sign2(yu,yd)>=0) & (yu<=yd))[0]

# xu,xd,yu,yd=(x-lane_x[:,0]),np.diff(lane_x).T[0],(y-lane_y[:,0]),np.diff(lane_y).T[0]
cLaneID=[np.where((sign2((x-lane_x[:,0]),np.diff(lane_x).T[0])>=0) & ((x-lane_x[:,0])<=np.diff(lane_x).T[0]) & (sign2((y-lane_y[:,0]),np.diff(lane_y).T[0])>=0) & ((y-lane_y[:,0])<=np.diff(lane_y).T[0]))[0] 
 for x,y in zip(initPx,initPy)]



# for j in range(NofC):
#     currPosMo=Rot(cPos(j,3)-pi/2)*Moby+repmat(cPos(j,1:2)',[1 size(Moby,2)]);
#     pc{j,1}=plot(currPosMo(1,:),currPosMo(2,:),'-','LineWidth',3,'color',ccol(j,:)); 
#     pc{j,2}=plot(cPos(j,1),cPos(j,2),'.','MarkerSize',22); 
# end

In [ ]:
np.empty([1,3])
initPx=np.array([-80,   0.1])
initPx

In [ ]:
cPos=np.empty([NofC,3])
display(cPos)
np.vstack([initPx,initPy]).T

In [ ]:
cPos[:,:2]
cLaneID=[np.where((sign2((x-lane_x[:,0]),np.diff(lane_x).T[0])>=0) & ((x-lane_x[:,0])<=np.diff(lane_x).T[0]) & (sign2((y-lane_y[:,0]),np.diff(lane_y).T[0])>=0) & ((y-lane_y[:,0])<=np.diff(lane_y).T[0]))[0] 
 for x,y in zip(initPx,initPy)]
cLaneID2=np.array(cLaneID)
np.array(angL)[cLaneID2]

In [ ]:
cPos=np.empty([NofC,3])
cPos[:,:2]=np.vstack([initPx,initPy]).T
# cPos[:,2]=np.array(angL)[cLaneID2]
cPos[:,2]=np.array(angL)[cLaneID2].T
cPos

In [ ]:
Rot(cPos[j,2]-np.pi/2)

In [ ]:
Moby=3*np.array([[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])  
# Moby=[]
Moby

In [ ]:
np.dot(Rot(cPos[j,2]-np.pi/2),Moby)

In [ ]:
np.shape(Moby)[1]


In [ ]:
[cPos[0,:2]]

In [ ]:
np.tile(cPos[0,:2],[np.shape(Moby)[1],1]).T

In [ ]:
for j in range(NofC):
    # currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+repmat(cPos(j,1:2)',[1 size(Moby,2)]);
    currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+np.tile(cPos[0,:2],[np.shape(Moby)[1],1]).T
currPosMo

In [8]:
figNum=20
fig = plt.figure(figNum)
fig.clear()
plt.cla()
maxR=[-100,100]
NofC=2

Moby=3*np.array([[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])      
Rot=lambda t: np.array([[np.cos(t),-np.sin(t)],[np.sin(t),np.cos(t)]])
cLen=np.abs(min(Moby[1,:])-max(Moby[1,:]))


cPos=np.empty([NofC,3])
cPos[:,:2]=np.vstack([initPx,initPy]).T
cPos[:,2]=np.array(angL)[cLaneID2].T

for j in range(NofC):
    # currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+repmat(cPos(j,1:2)',[1 size(Moby,2)]);
    currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+np.tile(cPos[j,:2],[np.shape(Moby)[1],1]).T
    plt.plot(currPosMo[0],currPosMo[1],'k-',linewidth=2)


for p2,p1 in zip(rotXY4[:len(rotXY)],rotXY4[len(rotXY):]):
    plt.plot(np.vstack([p1[:,0],p2[:,0]]),np.vstack([p1[:,1],p2[:,1]]),'-',linewidth=2)

plot_frames = []
my_color1=np.array([122,122,122])
# plt.plot(lane_x,lane_y,color=my_color1,lineWidth=3)
plt.plot(lane_x.T,lane_y.T,'--',color="0.5",linewidth=2)


# plt.xticks(np.arange(maxR[0], maxR[1], 10))
# plt.yticks(np.arange(maxR[0], maxR[1], 10))
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')

# def plotP(i2):
#     plt.cla() 
#     plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)
#     tP=i2/simT
#     tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
#     tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))

#     each_plot=[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]
#     plot_frames.append(each_plot)

# animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20, repeat=False)
# # animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20)

# plt.show()

# fig.legend(all_Lable)

(-110.0, 110.0, -110.0, 110.0)

In [17]:
figNum=21
fig = plt.figure(figNum)
fig.clear()
plt.cla()
maxR=[-100,100]

Moby=3*np.array([[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6],
                 [1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75]])      
Rot=lambda t: np.array([[np.cos(t),-np.sin(t)],[np.sin(t),np.cos(t)]])
display(Rot(np.pi))

cLen=np.abs(min(Moby[1,:])-max(Moby[1,:]))
roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label
roadW=10
simT=100
NofC=2

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0
initPx=v_planning_x[:,0]
initPy=v_planning_y[:,0]

display(initPx)

sign2=lambda a,b: np.sign(((a>=0).astype(int)-0.5)*((b>=0).astype(int)-0.5))

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

lane_x = mapDx.copy()
lane_y = mapDy.copy()

cLaneID=[np.where((sign2((x-lane_x[:,0]),np.diff(lane_x).T[0])>=0) & ((x-lane_x[:,0])<=np.diff(lane_x).T[0]) & (sign2((y-lane_y[:,0]),np.diff(lane_y).T[0])>=0) & ((y-lane_y[:,0])<=np.diff(lane_y).T[0]))[0] 
 for x,y in zip(initPx,initPy)]
cLaneID2=np.array(cLaneID)

vecR=[np.sqrt(np.diff(x)**2+np.diff(y)**2).T for x,y in zip(lane_x,lane_y)]
angL=[np.arctan2(np.diff(y),np.diff(x)) for x,y in zip(lane_x,lane_y)]
Rvec=[np.dot(Rot(-th).reshape(2,2),[np.diff(x),np.diff(y)]).T for x,y,th in zip(lane_x,lane_y,angL)]

rotXY=[np.tile(v,[2,1])+roadW/2*np.array([[0,0],[-1,1]]).T for v in Rvec]
rotXY2=[v-r*np.array([[1,1],[0,0]]).T for v,r in zip(rotXY,vecR)]
rotXY3=[np.dot(Rot(th).reshape(2,2),v.T).T for v,th in zip(rotXY+rotXY2,np.array(angL*2))]
rotXY4=[v+np.array([[x]*2,[y]*2]).T for v,x,y in zip(rotXY3,(np.tile(lane_x[:,0],[1,2])[0]).tolist(),(np.tile(lane_y[:,0],[1,2])[0]).tolist())]

cPos=np.empty([NofC,3])
cPos[:,:2]=np.vstack([initPx,initPy]).T
cPos[:,2]=np.array(angL)[cLaneID2].T

plot_frames = []
my_color1=np.array([122,122,122])

plt.title("Time")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
plt.axis('equal')

def plotP(i2):
    plt.cla() 
    plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

    for p2,p1 in zip(rotXY4[:len(rotXY)],rotXY4[len(rotXY):]):
        plt.plot(np.vstack([p1[:,0],p2[:,0]]),np.vstack([p1[:,1],p2[:,1]]),'-',linewidth=2)

    my_color1=np.array([122,122,122])
    # plt.plot(lane_x,lane_y,color=my_color1,lineWidth=3)
    plt.plot(lane_x.T,lane_y.T,'--',color="0.5",linewidth=2)

    # plt.title("Time")   # title of the plot
    plt.title(f'Time: {i2}')
    plt.xlabel("x")      # label in x axis
    plt.ylabel("y")      # label in y axis
    
    plt.xlim(maxR)   # range in x axis
    plt.ylim(maxR)     # range in x axis
    plt.axis('equal')

    # plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)
    tP=i2/simT
    tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
    tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))

    cPos[:,:2]=np.vstack([tmpx,tmpy]).T
    # cPos[:,2]=np.array(angL)[cLaneID2].T

    each_plot=[]
    for j in range(NofC):
        # currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+repmat(cPos(j,1:2)',[1 size(Moby,2)]);
        currPosMo=np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+np.tile(cPos[j,:2],[np.shape(Moby)[1],1]).T
        each_plot.append(plt.plot(currPosMo[0],currPosMo[1],'k-',linewidth=2))


    each_plot2=[plt.plot(x,y,'.',markersize=10) for x,y in zip(tmpx,tmpy)]
    each_plot3=each_plot+each_plot2
    
    plot_frames.append(each_plot3)

animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 100, repeat=False)
# # animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20)

plt.show()

fig.legend(all_Lable)

array([[-1.0000000e+00, -1.2246468e-16],
       [ 1.2246468e-16, -1.0000000e+00]])

array([-80,   0])

In [11]:
np.dot(Rot(cPos[j,2]-np.pi/2),Moby)+np.tile(cPos[j,:2],[np.shape(Moby)[1],1]).T

ValueError: shapes (2,2) and (6,10) not aligned: 2 (dim 1) != 6 (dim 0)

In [14]:
Moby

array([[-0.6 ,  0.6 ,  1.  ,  1.  ,  0.75, -0.75, -1.  , -1.  , -0.6 ,
         0.6 ],
       [ 1.75,  1.75,  0.75, -1.25, -1.55, -1.55, -1.25,  0.75,  1.75,
         1.75],
       [-0.6 ,  0.6 ,  1.  ,  1.  ,  0.75, -0.75, -1.  , -1.  , -0.6 ,
         0.6 ],
       [ 1.75,  1.75,  0.75, -1.25, -1.55, -1.55, -1.25,  0.75,  1.75,
         1.75],
       [-0.6 ,  0.6 ,  1.  ,  1.  ,  0.75, -0.75, -1.  , -1.  , -0.6 ,
         0.6 ],
       [ 1.75,  1.75,  0.75, -1.25, -1.55, -1.55, -1.25,  0.75,  1.75,
         1.75]])

In [5]:
cPos[:,2]

array([0.        , 1.57079633])

In [ ]:
currPosMo

In [ ]:
cLaneID=[np.where((sign2((x-lane_x[:,0]),np.diff(lane_x).T[0])>=0) & ((x-lane_x[:,0])<=np.diff(lane_x).T[0]) & (sign2((y-lane_y[:,0]),np.diff(lane_y).T[0])>=0) & ((y-lane_y[:,0])<=np.diff(lane_y).T[0]))[0] 
 for x,y in zip(initPx,initPy)]
cLaneID

In [ ]:
np.array(cLaneID)[0]

In [ ]:
[np.where((sign2((x-lane_x[:,0]),np.diff(lane_x).T[0])>=0) & ((x-lane_x[:,0])<=np.diff(lane_x).T[0]) & (sign2((y-lane_y[:,0]),np.diff(lane_y).T[0])>=0) & ((y-lane_y[:,0])<=np.diff(lane_y).T[0]))[0] for x,y in zip(initPx,initPy)]


In [ ]:
np.sign(-1)>0

In [ ]:
initPx[0],initPy[0]

In [ ]:
xu,xd,yu,yd=(initPx[0]-lane_x[:,0]),np.diff(lane_x).T[0],(initPy[0]-lane_y[:,0]),np.diff(lane_y).T[0]

In [ ]:
np.where((np.sign(xu*xd)>=0) & (xu<=xd) & (np.sign(yu*yd)>=0) & (yu<=yd))

In [ ]:
lane_x,lane_y

In [ ]:
sign2=lambda x: np.sign(x) if len(np.where(xu==0)[0])==0 else 1
sign2(0)

In [ ]:
sign2=lambda a,b: np.sign(((a>=0).astype(int)-0.5)*((b>=0).astype(int)-0.5))

In [ ]:
yu=np.array([  0, 0, -80])
yu

In [ ]:
yu[np.where(yu==0)[0]]=np.tile(0.1,[1,2])
yu[np.where(yu==0)[0]]

yu[np.where(yu==0)[0]]
# yu[np.where(yu==0)[0]]

In [ ]:
yu[np.where(yu==0)[0]]

In [ ]:
yu[0]=yu[0]+0.1
yu[0]

In [ ]:
yu[0]=yu[0]+0.1
[ for k in np.where(yu==0)[0]]

In [ ]:
yu,yd

In [ ]:
np.sign(((yu>=0).astype(int)-0.5)*((yd>=0).astype(int)-0.5))


In [ ]:
((yu>=0).astype(int)-0.5)

In [ ]:
((yd>=0).astype(int)-0.5)

In [ ]:
(yu>=0).astype(int)

In [ ]:
(yu>=0) & (yd>=0)

In [ ]:
yu[0]=0.1
yd[2]=-10
yd

In [ ]:
sign2(xu)*sign2(xd)

In [ ]:
sign2=lambda a,b: np.sign(((a>=0).astype(int)-0.5)*((b>=0).astype(int)-0.5))
np.where((sign2(xu,xd)>=0) & (xu<=xd) & (sign2(xu,xd)>=0) & (yu<=yd))[0]

In [ ]:
np.sign(xu*xd)>=0

In [ ]:
xu<=xd

In [ ]:
np.sign(yu*yd)>=0

In [ ]:
yu<=yd

In [ ]:
(initPx[0]-lane_x[:,0])

In [ ]:
np.diff(lane_x).T[0]

In [ ]:
(initPx[0]-lane_x[:,0])*np.diff(lane_x).T[0]>=0

In [ ]:
np.sign()

In [ ]:
(initPx[0]-lane_x[:,0])<np.diff(lane_x).T[0]

In [ ]:
lane_x-initPx[0]

In [ ]:
np.array(rotXY3).reshape(len(lane_x)*4,2).T

In [ ]:
np.array(rotXY3)

In [ ]:
len(rotXY)

In [ ]:
len(rotXY+rotXY2)

In [ ]:
len(lane_x)*4

In [ ]:
k=1
v=rotXY[k]
th=angL[k]
np.dot(Rot(th).reshape(2,2),v.T)

In [ ]:
Rot(th).reshape(2,2)

In [ ]:
v.T

In [ ]:
angL=[np.arctan2(np.diff(y),np.diff(x)) for x,y in zip(lane_x,lane_y)]
angL=[np.dot(Rot(-np.arctan2(np.diff(y),np.diff(x))),[np.diff(y),np.diff(x)]) for x,y in zip(lane_x,lane_y)]
# [Rot(-a) for a in angL]

In [ ]:
figNum=17
maxR=[-100,100]
fig = plt.figure(figNum)

Moby=np.array(3*[-0.6, 0.6,   1,    1, 0.75,-0.75,   -1,  -1,-0.6,0.6;1.75,1.75,0.75,-1.25,-1.55,-1.55,-1.25,0.75,1.75,1.75];      
Rot=@(t) [cos(t),-sin(t); sin(t),cos(t)];
cLen=abs(min(Moby(2,:))-max(Moby(2,:)));

fig.clear()
plt.cla()
plot_frames = []

v_planning_x=np.array([[-80,80],[ 0,0]])
v_planning_y=np.array([[0,0],[-80,80]])
tP=0

cPx=v_planning_x[:,1]*tP+v_planning_x[:,0]*[1-tP]
cPy=v_planning_y[:,1]*tP+v_planning_y[:,0]*[1-tP]

roadLabel=['road1','road2','road3'];
vehi_Label=['vehicle1','vehicle2'];
all_Lable=roadLabel+vehi_Label

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

# plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)

simT=100
NofC=2

def plotP(i2):
    plt.cla() 
    plt.plot(mapDx.T,mapDy.T,'-',linewidth=2)
    tP=i2/simT
    tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
    tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))

    each_plot=[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]
    plot_frames.append(each_plot)

animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20, repeat=False)
# animatedP = animation.FuncAnimation(fig, plotP, interval=100,frames = 20)

plt.show()

fig.legend(all_Lable)

In [ ]:
tmpx=np.dot(v_planning_x,np.array([1-tP,tP]))
tmpy=np.dot(v_planning_y,np.array([1-tP,tP]))
tmpx
[plt.plot(x,y,'.',markersize=20) for x,y in zip(tmpx,tmpy)]

In [ ]:
[v_planning_x].T

In [ ]:
[[1-tP,tP]].T

In [ ]:
https://numpy.org/doc/2.1/reference/generated/numpy.dot.html
https://numpy.org/doc/2.1/reference/generated/numpy.matmul.html#numpy.matmul

In [ ]:
https://qiita.com/Yuu-Miino/items/ae7d9c78bc2dff6c9a51

In [ ]:
np.dot(v_planning_x[1],np.array([1-tP,tP]))

In [ ]:

NofC=2;
simT=100;
vC=[50,40]; # %50km/h*1000(k)/3600(s)
#% frate=0.1;
frate=1

v_planning_x=[-80,80; 0,0;];
v_planning_y=[0,0;-80,80;];
tP=0;

cPx=v_planning_x(:,2).*tP+v_planning_x(:,1).*(1-tP);
cPy=v_planning_y(:,2).*tP+v_planning_y(:,1).*(1-tP);

roadLabel={'road1','road2','road3'};
vehi_Label={'vehicle1','vehicle2'};
all_Lable=roadLabel;
all_Lable(end+1:end+length(vehi_Label))=vehi_Label;

mapDx=np.array([[-100,100],[0,0],[0,100]])
mapDy=np.array([[0,0],[-100,100],[80,80]])

plot(mapDx',mapDy','LineWidth',2),hold on;

vehiP={};
for i=1:NofC
    vehiP{i}=plot(cPx(i)',cPy(i)','.','Color',myCol(i,:),'MarkerSize',50);
end

legend(all_Lable);
grid on;
axis equal;
tPv=repmat(tP,[1,2]);

for i2=1:simT
% %     tPv=tPv+(vC*1000/3600).*frate;
    tP=i2/simT;
    tPv=repmat(tP,[1,2]);
    tmpx=diag(v_planning_x*[(1-tPv);tPv]);
    tmpy=diag(v_planning_y*[(1-tPv);tPv]);
    
    for i=1:NofC
        set(vehiP{i},'XData',tmpx(i),'YData',tmpy(i));
    end
%     pause(0.1);
    drawnow;
end
