In [1]:
## Python basics for novice data scientists, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2020 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2022-12-29 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2A_python_basic_course
# # @IDE     : Python 3.9.16 (main, Dec  7 2022, 10:15:43) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : lec2_step02.py 

In [1]:
# module test: if you have an error when you run this code, 
# you need to check the installation status of those modules

import math 
import sys 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tkinter as tk

In [2]:
import matplotlib.pyplot as plt
%matplotlib tk

In [3]:
# frame = tk.Frame(self.master)
# matplotlib tk
fig = plt.figure(1)
fig.clf(True)

plt.xticks(np.arange(-3, 3, 1))
plt.yticks(np.arange(-1, 1, 1))
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

x = np.arange(-3.14, 3.14, 0.1)
y = np.sin(x)
plt.plot(x, y,'.')

# ax.plot([1, 2, 3])
# plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
  


In [5]:
# frame = tk.Frame(self.master)
# matplotlib tk
fig = plt.figure(2)
fig.clf(True)

plt.xticks(np.arange(-np.pi, 2*np.pi, np.pi/2),[ "-pi", "-pi/2", "0", "pi/2", "pi", "2*pi"])
plt.yticks(np.arange(-1, 1, 1))
plt.tick_params(width = 2, length = 10)

plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

x = np.arange(-np.pi, np.pi, 0.1)
y = np.sin(x)
plt.plot(x, y,'.')

plt.title("y=sin(x)")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(-np.pi-0.1, np.pi+0.1)   # range in x axis
plt.ylim(-1.1,   1.1)     # range in x axis
  


(-1.1, 1.1)

In [4]:
np.arange(-np.pi, 2*np.pi, np.pi/2)

array([-3.14159265, -1.57079633,  0.        ,  1.57079633,  3.14159265,
        4.71238898])

In [5]:
fig = plt.figure(3)
fig.clf(True)

# plt.xticks(np.arange(-np.pi, 2*np.pi, np.pi/2),[ "-π", "-π/2", "0", "π/2", "π", "2π"],fontname='sans-serif')
plt.xticks(np.arange(-np.pi, 2*np.pi, np.pi/2),[ "-π", "-π/2", "0", "π/2", "π", "2π"],fontname='Times',fontsize=14)
plt.yticks(np.arange(-1, 1, 1))
plt.tick_params(width = 2, length = 10)

plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

x = np.arange(-np.pi, np.pi, 0.1)
y = np.sin(x)
plt.plot(x, y,'.')

plt.title("y=sin(x)")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(-np.pi-0.1, np.pi+0.1)   # range in x axis
plt.ylim(-1.1,   1.1)     # range in x axis
  


(-1.1, 1.1)

In [8]:
dataD=np.array([[1, -1,-1,1],[1,1,-1,-1]])
dataD
print(dataD[0])
print(dataD[1])

[ 1 -1 -1  1]
[ 1  1 -1 -1]


In [9]:
fig = plt.figure()
# figrue(3); clf; # matlab 


In [10]:
maxR=np.array([-5,5])
np.arange(maxR[0], maxR[1]+1, 1)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [6]:
fig = plt.figure(4)
fig.clf(True)

NofD=4
maxR=np.array([-5,5])

plt.xticks(np.arange(maxR[0], maxR[1], 1))
plt.yticks(np.arange(maxR[0], maxR[1], 1))
plt.axis('equal')

plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

dataD=np.array([[1, -1,-1,1],[1,1,-1,-1]])

plt.plot(dataD[0], dataD[1],'k.',markersize=12)

plt.title("Points")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis

(-5.0, 5.0)

In [12]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
P=np.array([[-2],[2]])
np.tile(P,[1,3])

array([[-2, -2, -2],
       [ 2,  2,  2]])

In [12]:
def rotA_f(th):
    return [[np.cos(th), -np.sin(th)],[np.sin(th),np.cos(th)]]

rotA_f(np.pi)

[[-1.0, -1.2246467991473532e-16], [1.2246467991473532e-16, -1.0]]

In [13]:
rotA=lambda th: [[np.cos(th), -np.sin(th)],[np.sin(th),np.cos(th)]]
# [MATLAB] rotA=@(th) [cos(th) -sin(th); sin(th) cos(th)];

rotA(np.pi)

[[-1.0, -1.2246467991473532e-16], [1.2246467991473532e-16, -1.0]]

In [14]:
fig = plt.figure(5)
fig.clf(True)

NofD=4
maxR=np.array([-5,5])

plt.xticks(np.arange(maxR[0], maxR[1], 1))
plt.yticks(np.arange(maxR[0], maxR[1], 1))
plt.axis('equal')

plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

plt.title("Points")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis

dataD=np.array([[1, -1,-1,1],[1,1,-1,-1]])
print(dataD)
plt.plot(dataD[0], dataD[1],'k.',markersize=12)

plt.show()

dataD=np.dot(rotA(np.pi/4),dataD)
print(dataD)
plt.plot(dataD[0], dataD[1],'r.',markersize=12)

plt.show()

[[ 1 -1 -1  1]
 [ 1  1 -1 -1]]
[[ 1.11022302e-16 -1.41421356e+00 -1.11022302e-16  1.41421356e+00]
 [ 1.41421356e+00  1.11022302e-16 -1.41421356e+00 -1.11022302e-16]]


In [15]:
# frame = tk.Frame(self.master)
# matplotlib tk
fig = plt.figure(6)
fig.clf(True)

NofD=4
maxR=np.array([-5,5])

plt.xticks(np.arange(maxR[0], maxR[1], 1))
plt.yticks(np.arange(maxR[0], maxR[1], 1))
plt.axis('equal')

plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

plt.title("Points")   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis


dataD=np.array([[1, -1,-1,1],[1,1,-1,-1]])
print(dataD)
plt.plot(dataD[0], dataD[1],'k.',markersize=12)

plt.show()

fig.clf(True)
plt.cla()  
plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)
plt.xticks(np.arange(maxR[0], maxR[1], 1))
plt.yticks(np.arange(maxR[0], maxR[1], 1))
plt.axis('equal')
plt.xlim(maxR)   # range in x axis
plt.ylim(maxR)     # range in x axis
         
dataD=np.dot(rotA(np.pi/4),dataD)
print(dataD)
plt.plot(dataD[0], dataD[1],'r.',markersize=12)

plt.show()
      


[[ 1 -1 -1  1]
 [ 1  1 -1 -1]]
[[ 1.11022302e-16 -1.41421356e+00 -1.11022302e-16  1.41421356e+00]
 [ 1.41421356e+00  1.11022302e-16 -1.41421356e+00 -1.11022302e-16]]


In [8]:
# code from https://matplotlib.org/stable/gallery/animation/pause_resume.html

import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np


class PauseAnimation:
    def __init__(self):
        fig, ax = plt.subplots()
        ax.set_title('Click to pause/resume the animation')
        x = np.linspace(-0.1, 0.1, 1000)

        # Start with a normal distribution
        self.n0 = (1.0 / ((4 * np.pi * 2e-4 * 0.1) ** 0.5)
                   * np.exp(-x ** 2 / (4 * 2e-4 * 0.1)))
        self.p, = ax.plot(x, self.n0)

        self.animation = animation.FuncAnimation(
            fig, self.update, frames=200, interval=50, blit=True)
        self.paused = False

        fig.canvas.mpl_connect('button_press_event', self.toggle_pause)

    def toggle_pause(self, *args, **kwargs):
        if self.paused:
            self.animation.resume()
        else:
            self.animation.pause()
        self.paused = not self.paused

    def update(self, i):
        self.n0 += i / 100 % 5
        self.p.set_ydata(self.n0 % 20)
        return (self.p,)


pa = PauseAnimation()
plt.show()

In [19]:
# Latex based text visualization ---
# if the install problem exist, it does not work 
# ================================================

In [20]:
# frame = tk.Frame(self.master)
# matplotlib tk
fig = plt.figure(3)
fig.clf(True)
# plt.rcParams['text.usetex'] = True

plt.xticks(np.arange(-np.pi, 2*np.pi, np.pi/2),[ "-pi", "-pi/2", "0", "pi/2", "pi", "2*pi"])
plt.yticks(np.arange(-1, 1, 1))
plt.tick_params(width = 2, length = 10)

plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

x = np.arange(-np.pi, np.pi, 0.1)
y = np.sin(x)
plt.plot(x, y,'.')

# plt.title(r'\textbf{time (s)}')   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(-np.pi-0.1, np.pi+0.1)   # range in x axis
plt.ylim(-1.1,   1.1)     # range in x axis
  


(-1.1, 1.1)

In [21]:
# frame = tk.Frame(self.master)
# matplotlib tk
fig = plt.figure(4)
fig.clf(True)
# plt.rcParams['text.usetex'] = True
# cbformat = ticker.ScalarFormatter(useMathText=True)
plt.rc('text', usetex=True)

plt.xticks(np.arange(-np.pi, 2*np.pi, np.pi/2),[ "-pi", "-pi/2", "0", "pi/2", "pi", "2*pi"])
plt.yticks(np.arange(-1, 1, 1))
plt.tick_params(width = 2, length = 10)

plt.grid(color=[0.5,0.5,0.5], linestyle='-', linewidth=0.5)

x = np.arange(-np.pi, np.pi, 0.1)
y = np.sin(x)
plt.plot(x, y,'.')

# plt.title(r'\textbf{time (s)}')   # title of the plot
plt.xlabel("x")      # label in x axis
plt.ylabel("y")      # label in y axis

plt.xlim(-np.pi-0.1, np.pi+0.1)   # range in x axis
plt.ylim(-1.1,   1.1)     # range in x axis
  


(-1.1, 1.1)

In [22]:
# code from https://matplotlib.org/stable/tutorials/text/pgf.html

import matplotlib.pyplot as plt
plt.rcParams.update({
    "pgf.texsystem": "pdflatex",
    "pgf.preamble": "\n".join([
         r"\usepackage[utf8x]{inputenc}",
         r"\usepackage[T1]{fontenc}",
         r"\usepackage{cmbright}",
    ]),
})

fig, ax = plt.subplots(figsize=(4.5, 2.5))

ax.plot(range(5))

ax.text(0.5, 3., "serif", family="serif")
ax.text(0.5, 2., "monospace", family="monospace")
ax.text(2.5, 2., "sans-serif", family="sans-serif")
ax.set_xlabel(r"µ is not $\mu$")

fig.tight_layout(pad=.5)

RuntimeError: latex was not able to process the following string:
b'lp'

Here is the full report generated by latex:
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=latex)
---! /usr/local/share/texmf-var/web2c/latex.fmt was written by pdfetex
(Fatal format file error; I'm stymied)




In [ ]:
"""
============
PGF preamble
============
"""

import matplotlib as mpl
mpl.use("pgf")
import matplotlib.pyplot as plt
plt.rcParams.update({
    "font.family": "serif",  # use serif/main font for text elements
    "text.usetex": True,     # use inline math for ticks
    "pgf.rcfonts": False,    # don't setup fonts from rc parameters
    "pgf.preamble": "\n".join([
         r"\usepackage{url}",            # load additional packages
         r"\usepackage{unicode-math}",   # unicode math setup
         r"\setmainfont{DejaVu Serif}",  # serif font via preamble
    ])
})

fig, ax = plt.subplots(figsize=(4.5, 2.5))

ax.plot(range(5))

ax.set_xlabel("unicode text: я, ψ, €, ü")
ax.set_ylabel(r"\url{https://matplotlib.org}")
ax.legend(["unicode math: $λ=∑_i^∞ μ_i^2$"])

fig.tight_layout(pad=.5)

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/matplotlib/texmanager.py", line 252, in _run_checked_subprocess
    report = subprocess.check_output(
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/Users/hiro/.matplotlib/tex.cache/1acea6f6c115d0ec7a634ed0529287b9.tex']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Ver

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/matplotlib/texmanager.py", line 252, in _run_checked_subprocess
    report = subprocess.check_output(
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/Users/hiro/.matplotlib/tex.cache/1acea6f6c115d0ec7a634ed0529287b9.tex']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Ver